spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path= /product-service/**
        - id: order-service
          uri: lb://OTHER-SERVICE
          predicates:
            - Path= /other-service/**
        - id: inventory-service
          uri: http://localhost:3000
          predicates:
            - Path= /inventory-service/**
        - id: customer-service
          uri: http://localhost:5000
          predicates:
            - Path= /customer_service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/